### PR TITLE
Fixed setup breaks model binding

### PR DESCRIPTION
**Pull request by andresmatasuarez**
Github issue: https://github.com/angular-ui/ui-tinymce/issues/112
Solution: https://github.com/mangreen/ui-tinymce/pull/1

@mangreen did not make PR against angular-ui/ui-tinymce repository so I am making this fork just to make that PR so it gets merged into master and gets a proper release. Solution credits go to @mangreen.

### CODE REVIEW

**Comment by adrianthedev** [comment]
+1 please

**Comment by breity** [comment]
+1

**Comment by deeg** [comment]
+1 please

**Comment by deeg** [comment]
I think I am going to use the solution provided in #143 instead.

This will prevent us from overriding any other properties on the options object by keeping all original objects intact.

Will leave this open until the new release incase anyone has opinions on the matter.

**Comment by deeg** [comment]
This is in the new v.0.0.10 release.

**Comment by andresmatasuarez** [comment]
Great!

**Pull request closed without merging**
