### PR TITLE
Updating model on paste, cut, undo & redo

### PR DESCRIPTION
**Pull request by JulienCabanes**
This is similar to #144 but it also takes care of cut, undo and redo actions.

### CODE REVIEW

**Comment by ceilino** [comment]
+1

**Comment by deeg** [comment]
I don't mind adding this in, but will those actions not also fire a change event? What is not working for you if those other events are not there?

They all seem to work fine for me.

**Comment by CyborgMaster** [comment]
The problem seems to be with context menu initiated copy and paste.  In the current version if I highlight some text in the editor and then right click and select paste, the UI updates with the pasted text, but not the angular model.  If I initiate the paste with Ctrl(Command)-V, the model does update. With @JulienCabanes's branch, it works with the right click context menu.

**Comment by CyborgMaster** [comment]
Excellent.  Can we get a new version released? Then I can stop using @JulienCabanes's branch.

**Comment by deeg** [comment]
@CyborgMaster, I plan to do this tonight as I wanted to get one or two more fixes in before officially releasing a new version.

In the meantime you can tell bower to install the latest master branch:

``` bower install angular-ui-tinymce#master --save```

or in your bower.json file:

```"angular-ui-tinymce": "master"```

**Comment by CyborgMaster** [comment]
Thanks!  Looks like I should have just been a little more patient.  My apologies.

**Comment by deeg** [comment]
Sorry for the delay, this time of year is crazy. A new release has been put out.

Hope you had a good holidays, and have a happy new year!

**Pull request closed without merging**
