### PR TITLE
Added priority to directive

### PR DESCRIPTION
**Pull request by orzilca**
Fixes various problems causing the editor not to show up or not to respond to ng-model change

### CODE REVIEW

**Comment by karthikbalu** [comment]
This is a very high priority fix, can u please merge it ASAP pls
Thanks

**Comment by paivaric** [comment]
Please.. merge this... i need this too... tks!!!

**Comment by ryanberckmans** [comment]
This PR fixed my issue. I had `ng-model="some.object.property"`; updates weren't calling `ngModel.$render`; I set `priority: 999,`; now it works.

**Comment by deeg** [comment]
I hate to set an arbitrary priority for no reason. So far I have not found any instances where a priority helped me.

Do you think you could post a Plunker or FIddle demonstrating the issue? If it is really fixing issues for many people I don't mind getting it into the next release, I just want to make sure we have some reason for it.

**Comment by AGiorgetti** [comment]
Looking at the Angular code I'm pretty sure the problem is in redefining 'ngModel.$render' and the order of execution of the directives.
Assuming you have no priority uiTinymce will run with the same priority as angular 'textarea' directive (which is defined by the 'inputDirective' variable, just look in the Angular code).
The linking function of this angular directive is redefining the ngModel.$render function too which can sometimes override uiTinymce $render function (no execution order guaranteed with directive of the same priority).
The code I'm talking about is at this link:
https://github.com/angular/angular.js/blob/40c974ab148cdbb80bd0f470f0ebf70f0fb228d4/src/ng/directive/input.js#L1171

**Comment by fabian** [comment]
Can confirm that `priority` fixes it. I've created a Plunker that describes the exact problem from https://github.com/angular-ui/ui-tinymce/issues/223 (adding the line 8 also solves the problem):

http://plnkr.co/edit/gxnnI1IuJv8aFjgPGPcs?p=preview

**Comment by fabian** [comment]
Here's a Plunker showing the issue: http://plnkr.co/edit/gxnnI1IuJv8aFjgPGPcs

**Comment by deeg** [comment]
@fabian, thanks for posting the plunker.

I added priority with 999 for now, but I might change to a lower number if I hear it causes issues for people.

**Pull request closed without merging**
